name: Deploy GCP Infrastructure (split jobs)

on:
  workflow_dispatch:
    inputs:
      project_id:
        default: "dataops-466411"
        required: true
        description: "GCP Project ID"
      region:
        default: "europe-west1"
        required: true
        description: "GCP Region"
      bucket_name:
        default: "vale-dataops-bucket"
        required: true
        description: "GCS Bucket Name"
      composer_name:
        default: "vale-composer"
        required: true
        description: "Composer Environment Name"
      composer_image_version:
        default: "composer-3-airflow-2.10.5"
        required: true
        description: "Composer image version"
      dataproc_name:
        default: "vale-dataproc"
        required: true
        description: "Dataproc Cluster Name"
      dataproc_num_workers:
        default: "2"
        required: true
        description: "Number of workers"

jobs:
  gcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Apply GCS
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -target=module.gcs \
            -var="project_id=${{ github.event.inputs.project_id }}" \
            -var="region=${{ github.event.inputs.region }}" \
            -var="bucket_name=${{ github.event.inputs.bucket_name }}"

  composer:
    runs-on: ubuntu-latest
    needs: gcs
    steps:
      - uses: actions/checkout@v3

      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Apply Composer
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -target=module.composer \
            -var="project_id=${{ github.event.inputs.project_id }}" \
            -var="region=${{ github.event.inputs.region }}" \
            -var="composer_name=${{ github.event.inputs.composer_name }}" \
            -var="composer_image_version=${{ github.event.inputs.composer_image_version }}"

  dataproc:
    runs-on: ubuntu-latest
    needs: composer
    steps:
      - uses: actions/checkout@v3

      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Apply Dataproc
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -target=module.dataproc \
            -var="project_id=${{ github.event.inputs.project_id }}" \
            -var="region=${{ github.event.inputs.region }}" \
            -var="dataproc_name=${{ github.event.inputs.dataproc_name }}" \
            -var="dataproc_num_workers=${{ github.event.inputs.dataproc_num_workers }}"
